version: '3'

services:
  customer-service:
    image: customerservice:latest
    ports:
    - "8080:8080"
    networks:
      - my_network

  order-service:
    image: order-service:latest
    ports:
      - "8083:8083"
    networks:
      - my_network

  sale-service:
    image: sale-service:latest
    ports:
      - "8082:8082"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
